### ISSUE TITLE
[1.7.10] Mod not working with Advanced Rocketry

### ISSUE THREAD

**Issue by aking4125** [TCLProject/Biome-ID-Extender#2]
Hello,

Setting any Biome ID higher than 255 is not possible with as it crashes with this report: [crash-2022-04-12_20.48.16-client.txt](https://github.com/TCLProject/Biome-ID-Extender/files/8477383/crash-2022-04-12_20.48.16-client.txt)
 
Any ideas?

**Comment by TCLProject** [comment]
This is technically fixable, but Advanced Rocketry adds its own dimensions, so there will still be issues. As said in the description,
_Any mod which adds a dimension and custom biomes to it: [...] if you have ids higher 127 for these mods, their biomes spawn in the overworld._
So there's not much use in fixing this. Put the supported mods' biome IDs over 255 and let adv. rocketry and other dimension mods occupy spaces below 127

**Comment by HRudyPlayZ** [comment]
It doesn't and probably won't ever work with any mod that adds dimensions, at least not unless we can somehow find a way to prevent biomes above 127 to spawn in the overworld. (If so then, feel free to reopen the issue)
Don't expect this mod to work on any mod not listed on the Curseforge page, since biome ID changes need to be done on a per done basis ;)

**Comment by aking4125** [comment]
> This is technically fixable, but Advanced Rocketry adds its own dimensions, so there will still be issues. As said in the description, _Any mod which adds a dimension and custom biomes to it: [...] if you have ids higher 127 for these mods, their biomes spawn in the overworld._ So there's not much use in fixing this. Put the supported mods' biome IDs over 255 and let adv. rocketry and other dimension mods occupy spaces below 127

Copy that. Will give it a shot!
